version: "2"
services:
  keycloak:
    build: .
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    volumes:
      - "$PWD/scripts/disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli"
    ports:
      - "9900:8080"
volumes:
  db-data:
    driver: local